name: Playground
on:
  push:
    branches:
      - main
      
jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - uses: actions/checkout@v2
          
      - name: Run Playground
        run: bash pc.sh
      
      - uses: actions/checkout@v1
